// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_VhRcjMdlS9myXa2lkRPdsN0EpsHKwE',
    appId: '1:194581554520:web:77062454c107908069f12d',
    messagingSenderId: '194581554520',
    projectId: 'proyectomoviles-95017',
    authDomain: 'proyectomoviles-95017.firebaseapp.com',
    storageBucket: 'proyectomoviles-95017.appspot.com',
    measurementId: 'G-0NETBXW5D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ5ytQIlnchotnepIoEeeA_h_XoIHjax8',
    appId: '1:194581554520:android:b287a1dd08157afd69f12d',
    messagingSenderId: '194581554520',
    projectId: 'proyectomoviles-95017',
    storageBucket: 'proyectomoviles-95017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6gxbP9ijGNCqJjkMNBCoIJ9ZqovtWlY',
    appId: '1:194581554520:ios:50bc3506f0e12f8869f12d',
    messagingSenderId: '194581554520',
    projectId: 'proyectomoviles-95017',
    storageBucket: 'proyectomoviles-95017.appspot.com',
    iosBundleId: 'com.example.proyectoVsn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6gxbP9ijGNCqJjkMNBCoIJ9ZqovtWlY',
    appId: '1:194581554520:ios:52cb780082c5b6c469f12d',
    messagingSenderId: '194581554520',
    projectId: 'proyectomoviles-95017',
    storageBucket: 'proyectomoviles-95017.appspot.com',
    iosBundleId: 'com.example.proyectoVsn.RunnerTests',
  );
}
